local dirtylarry = require "dirtylarry.dirtylarry"

function init(self)
    msg.post(".", "acquire_input_focus")
end

function on_message(self, message_id, message, sender)
    if message_id == hash("proxy_loaded") then
        msg.post(sender, "enable")
    end
end

function on_input(self, action_id, action)
    dirtylarry:button("button_profiler", action_id, action, function()
        msg.post("@system:", "toggle_profile")
    end)
end
